apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm02
  namespace: default
spec:
  dataVolumeTemplates:
  - metadata:
    name: fedora-persist-dv
  spec:
    pvc:
      storageClassName: gp3-csi
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
    source:
      registry: 
        url: docker://quay.io/kubevirt/fedora-cloud-container-disk-demo
  instancetype:
    name: u1.small
  preference:
    name: fedora
  running: true
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices:
          interfaces:
            - masquerade: {}
              name: default
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          rng: {}
        machine:
          type: ""
        #resources:
        #  requests:
        #    memory: 1024M 
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/fedora-cloud-container-disk-demo
        name: containerdisk
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: fedora-0
            password: PASSWORD_GOES_HERE
            chpasswd: { expire: False }
            ssh_pwauth: True
            disable_root: false
        name: cloudinitdisk
